[package]
name = "baruwa"
version = "0.1.0"
edition = "2021"
authors = ["Mik Bry <mbry@miklabs.com>"]

[dependencies]

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
lto = true
#opt-level = 's'
#codegen-units = 1
panic = 'abort'
